name: C/C++ CI

on: [push, pull_request, schedule]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sudo apt-get install libgtk-3-dev -y && sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev zenity
    - name: build
      run: mkdir build; cd build; cmake ..; make; cp neutralino ../dist;

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build
